version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "3018:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: qwe123
